#!/usr/bin/env bash
# Use xRageTC build script as LLVM Build Script.
apt install bc \
            binutils-dev \
            bison \
            ca-certificates \
            ccache \
            clang \
            cmake \
            curl \
            file \
            flex \
            gcc \
            g++ \
            git \
            libelf-dev \
            libssl-dev \
            make \
            ninja-build \
            python3 \
            texinfo \
            u-boot-tools \
            xz-utils \
            zlib1g-dev -y
git clone https://github.com/awikwokproject/proton-clang-build -b master $(pwd)/llvmTC
cd $(pwd)/llvmTC
bash build-toolchain.sh
